name: Vale Linter with ReviewDog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:

          # This is the key change to remove 'Raw Output'
          reporter: github-pr-review

          # 'added' ensures Vale only comments on the lines the user actually changed
          # instead of flagging every existing typo in the whole file.
          filter_mode: added
          
          fail_on_error: true
        env:
          # Required, set by GitHub Actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
